#### Yugandhara Premraj Patil
#### Id : AIS031

#### Task 13 : Random Forest

In [37]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel
import numpy as np
np.random.seed(0)

In [38]:
iris=load_iris()
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df['species']=iris.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   species  
0        0  
1        0  
2        0  
3        0  
4        0

In [39]:
#create a List of featurenames
feat_labels=['Sepal Length','Sepal Width','Petal Length','Petal Width']
x=df.iloc[:,0:4]
y=df.iloc[:,4:5]
y=np.ravel(y)
# Split data into training and testing set in 70:30 ratio
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=0)

#### Generating Model

In [40]:
rfmc=RandomForestClassifier(n_estimators=100,random_state=0)
# training the classifier
rfmc.fit(x_train,y_train)
#Applying the train classifier to the test
y_pred=rfmc.predict(x_test)

In [41]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]


In [42]:
print('accuracy',accuracy_score(y_test,y_pred))

accuracy 0.9777777777777777


### Identify and select most important Feature

In [44]:
feature_importances=pd.DataFrame(rfmc.feature_importances_,index=x_train.columns,
                                 columns=['importance']).sort_values('importance',ascending=False)
feature_importances                                                                                                 

importance
petal length (cm)    0.479778
petal width (cm)     0.394131
sepal length (cm)    0.102444
sepal width (cm)     0.023647

In [45]:
#create selector object that will use the random forest classifier to identify feature that have an importance of more than 0.15
sfm=SelectFromModel(rfmc,threshold=0.15)

#train the selector
sfm.fit(x_train,y_train)

SelectFromModel(estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                                 class_weight=None,
                                                 criterion='gini',
                                                 max_depth=None,
                                                 max_features='auto',
                                                 max_leaf_nodes=None,
                                                 max_samples=None,
                                                 min_impurity_decrease=0.0,
                                                 min_impurity_split=None,
                                                 min_samples_leaf=1,
                                                 min_samples_split=2,
                                                 min_weight_fraction_leaf=0.0,
                                                 n_estimators=100, n_jobs=None,
                                                 oob_score=False,

In [46]:
for i in sfm.get_support(indices=True):
    print(feat_labels[i])

Petal Length
Petal Width


In [47]:
#create A data subset eith only the most important features
x_importance_train=sfm.transform(x_train)
x_importance_test=sfm.transform(x_test)
print(x_importance_train.shape)


(105, 2)


In [52]:
clf_important=RandomForestClassifier(n_estimators=100,random_state=0)
#Train a new random forest classifier using only most important features
clf_important.fit(x_importance_train,y_train)
#Applying the trained classifier to the test
y_important_pred=clf_important.predict(x_importance_test)
print(confusion_matrix(y_important_pred,y_test))

[[16  0  0]
 [ 0 17  0]
 [ 0  1 11]]


In [53]:
accuracy_score(y_test,y_important_pred)

0.9777777777777777