### Q.1. What is an array? 
### Ans.
>An array is collection of items stored at continous memory locations.The idea is to store multiple items of the same type together.This makes it easier to calculate the position of each element by simply adding am offsetto a base value,i.e. the memory loction of the first element of the array(generally denoted by the name of the array

### Q.2. What is the difference between array and list?
### Ans.
> Arrays and list both used in python to stored data,but they don't serve exactly the same purposes. <br>
>**The main difference between a list and array is the functions that you can perform to them.** <br>
>For example, you can divide an array by 3, and each number in an array will be dvided by 3 and result will be printed if you request it. If you try to divide a list by 3, Python will tell you thst it can't be done,and an error will be thrown.<br>
> Here's how it would work:

In [11]:
import numpy as np
x=np.array([3,6,9,12])
print(x/3.0)
y=[3,6,9,12]
print(y/3.0)

[1. 2. 3. 4.]


TypeError: unsupported operand type(s) for /: 'list' and 'float'

### Q.3. How to change the shape of an array?
### Ans.
>The reshape() function is used to change the shape of an array.<br>
>**syntax:**<br>
>numpy.reshape(a,newshape,order='C')

In [25]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
np.reshape(a,(4,2))


[[1 2 3 4]
 [5 6 7 8]]


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

### Q.4. What does the name.strip() do?
### Ans.
>strip() is an in-buit function in Python programming langauge that returns a copy of the string with both leading and trailing charcters removed (based on the string arguement passed).<br>
> **For example:**

In [37]:
name=""" greeks for greeks """
print(name)
# print the name by removing leading and trailing white spaces
print(name.strip())
# print the name by removing the characters greeks
print(name.strip(' greeks'))

 greeks for greeks 
greeks for greeks
fo


### Q.5. When we use triple single or triple double quotes to define a string?
### Ans.
>To create that span multiple lines, tripe single quotes or triple double quotes are use to enclos the string. <br>
> **code:**<br>
> ''' This string is on multiple lines within three single quotes on either side. '''<br>
>""" This string is on multiple lines within three double quotes on either side. """ <br>
>**output:**

In [45]:
print(''' This string is on 
multiple lines within 
three single quotes
on either side. ''')

 This string is on 
multiple lines within 
three single quotes
on either side. 


### Q.6. create a character type array?
### Ans.


In [48]:
import numpy as np
a=np.array([[A,B,C,D,E],[F,G,H,I,J]])

NameError: name 'A' is not defined